title: Theo Jaunet
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter:  #if your site has a twitter account, enter it here

# Author Settings
author: Theo Jaunet # add your name
author-img: prof.jpeg # add your photo
about-author: I'm a Ph.D. student at LIRIS and INSA-Lyon, interested in explainable AI with data visualization. # add description
social-twitter: jaunet_theo # add your Twitter handle
social-github: theo-jaunet # add your Github handle
social-linkedin: theo-jaunet
social-email: theo.jaunet.sio@gmail.com

# Tracker
analytics: UA-105697527-2

# Build Settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 99
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
