theme: jekyll-theme-minimal
logo: photo2.jpg
icon: favicon.ico
title: Theo Jaunet
github.is_user_page : https://github.com/Theo-Jaunet
google_analytics: 105697527
github_icon: github.png
mail_icon: mail.png
link_icon: linkdin.png
permalink:   /:categories/:title/